services:
  chainlit:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: dev
    container_name: chainlit
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./src:/app
      - ./transcripts:/app/transcripts
      - ./chainlit.db:/app/chainlit.db
    working_dir: /app
    restart: unless-stopped

  judge:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: judge
    container_name: judge
    env_file:
      - ./.env
    volumes:
      - ./src:/app
      - ./transcripts:/app/transcripts
    working_dir: /app
    profiles:
      - eval
    command: python -m evaluator.evaluator_v1